apiVersion: batch/v1
kind: CronJob
metadata:
  name: redditnotif
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redditnotif
            image: galonsky/redditnotif:latest
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: redditnotif-config
          restartPolicy: Never