apiVersion: batch/v1
kind: CronJob
metadata:
  name: redditnotif
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: redditnotif-config
            image: galonsky/redditnotif:v1.1.3
            imagePullPolicy: IfNotPresent
            name: redditnotif
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  startingDeadlineSeconds: 5
  successfulJobsHistoryLimit: 3
  suspend: false
