version: "3.9"
services:
  reddit-notif:
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  .: