# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build-docker:
    docker:
      - image: cimg/base:2024.06
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: configure and run buildx
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker buildx create --use
            docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t galonsky/redditnotif:latest -t galonsky/redditnotif:$CIRCLE_SHA1 .

  build-docker-tag:
    docker:
      - image: cimg/base:2024.06
    resource_class: arm.medium
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: configure and run buildx
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker buildx create --use
            docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t galonsky/redditnotif:$CIRCLE_TAG .
workflows:
  version: 2
  tests:
    jobs:
      - build-docker:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - build-docker-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
