# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build-docker:
    docker:
      - image: cimg/base:2024.06
    resource_class: medium
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build and push image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build -t galonsky/redditnotif:latest -t galonsky/redditnotif:$CIRCLE_SHA1 .
            docker push --all-tags galonsky/redditnotif

  build-docker-tag:
    docker:
      - image: cimg/base:2024.06
    resource_class: medium
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build and push image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build -t galonsky/redditnotif:$CIRCLE_TAG .
            docker push --all-tags galonsky/redditnotif
workflows:
  version: 2
  tests:
    jobs:
      - build-docker:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - build-docker-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
